import LocalizedStrings from 'react-native-localization';

export default new LocalizedStrings({
  en: {
    SignIn: {
      btnTitle: 'Sign In',
    },
    chooseLng: {
      title: 'Choose Your Language',
    },
    validation: {
      isRequired: 'field is required.',
      cant: 'cannot contain white spaces.',
      must: 'must be more than 2 characters long.',
      mustBe: 'must be a 10-digit number.',
      shouldContain: 'field should only contains number',
      digits: 'field should be of 4 digits',
      start: 'cannot start or end with a space.',
      invalid: 'field is invalid',
      and: 'and',
      notMatch: 'does not match',
      atleast: 'must be at least 3 characters',
    },
    settings: {
      title: 'Settings Page',
      notifi: 'Notifications',
      selctLang: 'Select language',
      fontSize: 'Font Size',
      small: 'Small',
      default: 'Default',
      large: 'Large',
      joinUs: 'Join Us Here',
      aboutUs: 'About Us',
      adver: 'Advertise',
      con: 'Contact Us',
      Privacy: 'Privacy Policy',
      enable: 'Enable/Disable Push Notification',
      chhose: 'Choose Your App Language',
      resetAll: 'Reset All News',
      small: 'small',
      default: 'default',
      large: 'large',
      system: 'System',
      light: 'Light',
      dark: 'Dark',
    },
    customDrawer: {
      dashbnoard: 'Dashboard',
      myProfile: 'My Profile',
      mySavedStory: 'My Saved Stories',
      myStory: 'My Stories',
      myRewards: 'My Rewards',
      myFeed: 'My Feed',
      settings: 'Settings',
      feedback: 'Feedback',
      rateUs: 'Rate Us',
      shareApp: 'Share App',
      signOut: 'Sign Out',
      disPre: 'Display Preference',
      default: 'Default',
      light: 'Light',
      dark: 'Dark',
      login: 'Login',
      areYou: 'Are you sure you want to logout?',
      yes: 'Yes',
      no: 'No',
      searchStory: 'Search Stories',
      guestUser: 'Guest User',
    },
    myProfile: {
      title: 'My Profile',
      name: 'Name',
      email: 'Email',
      mobile: 'Mobile',
      btnTitle: 'Update Profile',
      delAccount: 'Delete Account',
      changePassword: 'Change Password',
      otp: 'Otp',
      wehave: 'We have sent a verification code to',
      verify: 'Verify',
      verification: 'Verification',
      sending: 'Sending...',
      resend: 'Resend OTP',
      interest: 'Please select atleast one interest',
    },
    myRewards: {
      redeem: 'Redeem Points',
      manageReq: 'Manage Requests',
      avail: 'Available Reward Points',
      tranHis: 'Transaction History',
      youhaveNo: 'You have no transactions yet!',
      points: 'Points',
      date: 'Date',
      craeted: 'Created',
      noStory: 'No story attached',
      pointsReq: 'Points Required',
      reddem: 'Redeem',
      manageReq: 'Manage Requests',
      pointsRed: 'Points Redeeemed',
      accept: 'Accepted',
      pending: 'Pending',
      rejected: 'Rejected',
      offline: "You're offline.Please check your internet connection",
      noworr:
        "You're offline. No worries — your saved stories are still available for viewing.",
    },
    addFeedback: {
      title: 'Add Feedback',
      phnNum: 'Phone Number (Optional)',
      feedback: 'Feedback',
      submit: 'Submit',
      addStory: 'Add Story',
      savestor: 'To save the story please login',
      noDataFound: 'No data found',
      personalization: 'Please login to see the personalization news',
    },
    home: {
      welcome: 'Welcome',
      featSto: 'Featured Stories',
      filterby: 'Filter By Topics',
      allNews: 'All News',
      environ: 'Environment',
      entertain: 'Entertainment',
      science: 'Science',
      world: 'World',
      person: 'Personality',
      sports: 'Sports',
      social: 'Social',
      politics: 'Politics',
      busines: 'Business',
      other: 'Other',
      stayBlessed: 'Stay blessed & Connected',
      saveInt: 'Save Interests',
      title: 'Save your interests for better content & experience.',
      localNews: 'Local News',
      pressAgain: 'Press back again to exit.',
    },
    signIn: {
      title: 'Sign In',
      subTitle: 'Share Your News . Get Rewarded',
      email: 'Email',
      passwoed: 'Password',
      forgotpass: 'Forgot Password?',
      newUser: 'New user? ',
      signUp: 'Signup',
      continues: 'Continue as a ',
      guest: 'Guest',
      pressBack: 'Press back again to exit.',
      conPass: 'Confirm password',
    },
    signUp: {
      plsAccept: 'Please accept',
      terms: 'Terms & Conditions',
      and: 'and',
      privacy: 'Privacy Policy',
      already: 'Already have an account?',
      accept: 'Please accept Terms & Conditions and Privacy Policy',
    },
    Congo: {
      cong: 'Congratulations!',
      youHave: 'You have read all news ass per the Preferences you selected',
      swipeup: 'Swipe up to Read News From Other Category!',
    },
    Tutorial: {
      heading: 'Swipe Tutorial',
      up: 'Swipe Up: Next Story',
      down: 'Swipe Down: Previous Story',
      left: 'Swipe Left To Right: Go to Dashboard',
      right: 'Swipe Right To Left: Read Full Article',
      gotit: 'Got it!',
      write: 'Write your story...',
      done: 'Done',
      skipTutorial: 'Skip Tutorial',
    },
    Thanks: {
      title: 'Thanks for being with us',
      love: 'Love over app?',
      share:
        "Share our app with family and friends to amplify positivity and brighten everyone's day.",
      btnTitle: 'SHARE APP',
      submit: 'SUBMIT YOUR STORY',
    },
    AddStory: {
      story: 'Story',
      tap: 'Tap to add file',
      addFile: 'Add file',
      add: 'Add',
      toRem:
        'To remove this news,make sure to have an internet connection first',
      yourAcc: 'Your account has been deleted by admin.',
      copyTo: 'Copied to Clipboard',
      voucher: 'Voucher Code:',
      date: 'Date :',
      time: 'Time :',
      tapTo: 'Tap to know more',
      noLinks: 'No links available at the moment.',
    },
    cameraPer: {
      plsProvide: 'Please provide camera permission to use this feature.',
      notAvail:
        'This feature is not available (on this device / in this context)',
      stoPer: 'Please provide storage permission to use this feature.',
      blocked: 'Camera permission blocked. Please enable in settings.',
      camera: 'Camera',
      gallery: 'Gallery',
      camFea:
        'Camera feature is not available (on this device / in this context)',
    },
  },
  hi: {
    SignIn: {
      btnTitle: 'दाखिल करना',
    },
    chooseLng: {
      title: 'अपनी भाषा चुनें',
    },
    validation: {
      isRequired: 'फ़ील्ड आवश्यक है।',
      cant: 'सफ़ेद स्थान नहीं हो सकता।',
      must: 'कम से कम 2 अक्षर लंबा होना चाहिए।',
      mustBe: '10 अंकों की संख्या होनी चाहिए।',
      shouldContain: 'फ़ील्ड में केवल संख्याएँ होनी चाहिए।',
      digits: 'फ़ील्ड 4 अंकों का होना चाहिए।',
      start: 'शुरुआत या अंत में स्पेस नहीं हो सकता।',
      invalid: 'फ़ील्ड अमान्य है।',
      and: 'और',
      notMatch: 'मेल नहीं खाता।',
      atleast: 'कम से कम 3 अक्षर होने चाहिए',
    },

    settings: {
      title: 'सेटिंग्स पेज',
      notifi: 'सूचनाएं',
      selctLang: 'भाषा चुनें',
      fontSize: 'फॉन्ट साइज़',
      small: 'छोटा',
      default: 'मध्यम',
      large: 'बड़ा',
      joinUs: 'हमसे जुड़ें',
      aboutUs: 'हमारे बारे में',
      adver: 'विज्ञापन दें',
      con: 'संपर्क करें',
      Privacy: 'गोपनीयता नीति',
      enable: 'पुश नोटिफिकेशन चालू/बंद करें',
      chhose: 'अपने ऐप की भाषा चुनें',
      login: 'लॉगिन',
      resetAll: 'सभी समाचार रीसेट करें',
      small: 'छोटा',
      default: 'डिफ़ॉल्ट',
      large: 'बड़ा',
      system: 'सिस्टम',
      light: 'लाइट',
      dark: 'डार्क',
    },
    customDrawer: {
      dashbnoard: 'डैशबोर्ड',
      myProfile: 'मेरा प्रोफ़ाइल',
      mySavedStory: 'मेरी सेव की गई कहानियाँ',
      myStory: 'मेरी कहानियाँ',
      myRewards: 'मेरे पुरस्कार',
      myFeed: 'मेरा फ़ीड',
      settings: 'सेटिंग्स',
      feedback: 'प्रतिक्रिया',
      rateUs: 'हमें रेट करें',
      shareApp: 'ऐप शेयर करें',
      signOut: 'साइन आउट',
      disPre: 'डिस्प्ले प्रिफरेंस',
      default: 'डिफ़ॉल्ट',
      light: 'लाइट',
      dark: 'डार्क',
      login: 'लॉगिन',
      areYou: 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
      yes: 'हाँ',
      no: 'नहीं',
      searchStory: 'कहानियाँ खोजें',
      guestUser: 'अतिथि उपयोगकर्ता',
    },
    myProfile: {
      title: 'मेरा प्रोफ़ाइल',
      name: 'नाम',
      email: 'ईमेल',
      mobile: 'मोबाइल',
      btnTitle: 'प्रोफ़ाइल अपडेट करें',
      delAccount: 'खाता हटाएं',
      changePassword: 'पासवर्ड बदलें',
      otp: 'ओटीपी',
      wehave: 'हमने सत्यापन कोड भेजा है',
      verify: 'सत्यापित करें',
      verification: 'सत्यापन',
      sending: 'भेजा जा रहा है...',
      resend: 'ओटीपी दोबारा भेजें',
      interest: 'कृपया कम से कम एक रुचि चुनें',
    },
    myRewards: {
      redeem: 'पॉइंट्स रिडीम करें',
      manageReq: 'अनुरोध प्रबंधित करें',
      avail: 'उपलब्ध वॉलेट राशि',
      tranHis: 'लेन-देन का इतिहास',
      youhaveNo: 'अभी तक कोई लेन-देन नहीं हुआ है!',
      points: 'अंक',
      date: 'तारीख',
      craeted: 'बना हुआ',
      noStory: 'कोई कहानी संलग्न नहीं',
      pointsReq: 'आवश्यक अंक',
      reddem: 'रिडीम करें',
      manageReq: 'अनुरोध प्रबंधित करें',
      pointsRed: 'अंक रिडीम किए गए',
      accept: 'स्वीकृत',
      pending: 'प्रतीक्षारत',
      rejected: 'अस्वीकृत',

      offline: 'आप ऑफ़लाइन हैं.कृपया अपना इंटरनेट कनेक्शन जांचें',
      noworr:
        'आप ऑफ़लाइन हैं। चिंता न करें - आपकी सहेजी गई कहानियाँ अभी भी देखने के लिए उपलब्ध हैं।',
    },
    addFeedback: {
      title: 'प्रतिक्रिया जोड़ें',
      phnNum: 'फ़ोन नंबर (वैकल्पिक)',
      feedback: 'प्रतिक्रिया',
      submit: 'सबमिट करें',
      addStory: 'कहानी जोड़ें',
      savestor: 'कहानी सहेजने के लिए कृपया लॉगिन करें',
      noDataFound: 'कोई डेटा नहीं मिला',
      personalization: 'निजीकरण समाचार देखने के लिए कृपया लॉगिन करें',
    },
    home: {
      welcome: 'स्वागत है',
      featSto: 'फीचर्ड कहानियाँ',
      filterby: 'विषयों के अनुसार फ़िल्टर करें',
      allNews: 'सभी समाचार',
      environ: 'पर्यावरण',
      entertain: 'मनोरंजन',
      science: 'विज्ञान',
      world: 'दुनिया',
      person: 'व्यक्तित्व',
      sports: 'खेल',
      social: 'सामाजिक',
      politics: 'राजनीति',
      busines: 'व्यवसाय',
      other: 'अन्य',
      stayBlessed: 'आशीर्वादित रहें और जुड़े रहें',
      saveInt: 'रुचियाँ सहेजें',
      title: 'बेहतर सामग्री और अनुभव के लिए अपनी रुचियाँ सहेजें।',
      localNews: 'स्थानीय समाचार',
      pressAgain: 'बाहर निकलने के लिए पुनः वापस दबाएँ।',
    },
    signIn: {
      title: 'साइन इन करें',
      subTitle: 'अपनी खबर साझा करें । इनाम पाएं',
      email: 'ईमेल',
      passwoed: 'पासवर्ड',
      forgotpass: 'पासवर्ड भूल गए?',
      newUser: 'नया उपयोगकर्ता?',
      signUp: ' साइन अप करें',
      continues: 'जारी रखें एक',
      guest: ' मेहमान',
      pressBack: 'एग्ज़िट करने के लिए फिर से बैक दबाएँ।',
      conPass: 'पासवर्ड की पुष्टि करें',
    },

    signUp: {
      plsAccept: 'कृपया स्वीकार करें',
      terms: 'नियम और शर्तें',
      and: 'और',
      privacy: 'गोपनीयता नीति',
      already: 'पहले से ही खाता है?',
      accept: 'कृपया नियम और शर्तें तथा गोपनीयता नीति स्वीकार करें।',
    },
    Congo: {
      cong: 'बधाई हो!',
      youHave:
        'आपने अपनी चुनी हुई प्राथमिकताओं के अनुसार सारी खबरें पढ़ ली हैं',
      swipeup: 'अन्य श्रेणियों की खबरें पढ़ने के लिए ऊपर स्वाइप करें!',
    },
    Tutorial: {
      heading: 'स्वाइप ट्यूटोरियल',
      up: 'ऊपर स्वाइप करें: अगली कहानी',
      down: 'नीचे स्वाइप करें: पिछली कहानी',
      left: 'बाएं से दाएं स्वाइप करें: डैशबोर्ड पर जाएं',
      right: 'दाएँ से बाएं स्वाइप करें: पूरा लेख पढ़ें',
      gotit: 'समझ गया!',
      write: 'अपनी कहानी लिखें...',
      done: 'हो गया',
      skipTutorial: 'ट्यूटोरियल को छोड़ दें',
    },
    Thanks: {
      title: 'हमारे साथ रहने के लिए धन्यवाद',
      love: 'क्या आपको हमारा ऐप पसंद आया?',
      share:
        'हमारा ऐप परिवार और दोस्तों के साथ साझा करें ताकि सकारात्मकता फैले और सबका दिन बने।',
      btnTitle: 'ऐप साझा करें',
      submit: 'अपनी कहानी सबमिट करें',
    },
    AddStory: {
      story: 'कहानी',
      tap: 'फ़ाइल जोड़ने के लिए टैप करें',
      addFile: 'फ़ाइल जोड़ें',
      add: 'जोड़ें',
      toRem: 'इस समाचार को हटाने के लिए, पहले इंटरनेट कनेक्शन सुनिश्चित करें',
      yourAcc: 'आपका खाता व्यवस्थापक द्वारा हटा दिया गया है.',
      copyTo: 'क्लिपबोर्ड पर कॉपी किया गया',
      voucher: 'वाउचर कोड:',
      date: 'तारीख :',
      time: 'समय :',
      tapTo: 'अधिक जानने के लिए टैप करें',
      noLinks: 'फिलहाल कोई लिंक उपलब्ध नहीं है।',
    },
    cameraPer: {
      plsProvide: 'कृपया इस सुविधा का उपयोग करने के लिए कैमरा अनुमति दें।',
      notAvail: 'यह सुविधा उपलब्ध नहीं है (इस डिवाइस पर / इस संदर्भ में)।',
      stoPer: 'कृपया इस सुविधा का उपयोग करने के लिए स्टोरेज अनुमति दें।',
      blocked: 'कैमरा अनुमति अवरुद्ध है। कृपया सेटिंग्स में जाकर सक्षम करें।',
      camera: 'कैमरा',
      gallery: 'गैलरी',
      camFea: 'कैमरा सुविधा उपलब्ध नहीं है (इस डिवाइस पर / इस संदर्भ में)',
    },
  },
});
